---
- hosts: agent*
  gather_facts: False
  roles:
    - base

- hosts: agent*
  roles:
    - java

- hosts: agent*
  roles:
    - common

- hosts: agent*
  roles:
    - agent

- hosts: agent*
  roles:
    - docker
