---
- hosts: nexus
  gather_facts: False
  roles:
    - base

- hosts: nexus
  roles:
    - java

- hosts: nexus
  roles:
    - nexus

# DOCKER has to happen only after the build out of nexus (with a login)
- hosts: nexus
  roles:
    - docker
