---
- hosts: all
  roles:
    - common

- hosts: server
  roles:
    - server

- hosts: agents
  roles:
    - agent

- hosts: agents
  roles:
    - libs

- hosts: agents
  roles:
    - docker

# Now I just need a next instance and the glue to put all that shit together.
