---
- name: Apache2 install
  become: true
  apt: name={{ item }} state=installed
  with_items:
    - apache2
    - libxml2
    - libxml2-dev
    - build-essential

- name: Apache2 module setup for reverse proxy
  become: true
  apache2_module: name={{ item }} state=present
  with_items:
    - proxy
    - ssl
    - proxy_http
    - proxy_ajp
    - xml2enc
    - rewrite
    - deflate
    - headers
    - proxy_balancer
    - proxy_connect
    - proxy_html

- name: Create SSL directory
  file: path="/etc/apache2/ssl" state=directory owner=www-data group=www-data mode=0700 recurse=yes

- name: Copy in the cert request (make a slightly less trash cert)
  when: generate_http_cert == true
  copy:
    src: "req-input.cnf"
    dest: "/etc/apache2/ssl/req-input.cnf"
    mode: 0600

  #openssl req -x509 -config req-input.cnf -newkey rsa:4096 -sha256 -nodes -out nexus.pem -outform PEM
- name: HTTPs setup for nexus
  when: generate_http_cert == true
  command: openssl req -x509 -batch -nodes -days 1024 -newkey rsa:2048 -config /etc/apache2/ssl/req-input.cnf -keyout /etc/apache2/ssl/nexus.vm.key -out /etc/apache2/ssl/nexus.vm.crt -outform PEM

- name: Copy httpd vhost
  template: src="nexus-vhost.conf" dest="/etc/apache2/sites-available/nexus-vhost.conf"

- name: Change cert permissions if genreated
  when: generate_http_cert == true
  file:
    path: /etc/apache2/ssl/nexus.vm.crt
    mode: 0600

- name: Change cert key permissions if generated
  when: generate_http_cert == true
  file:
    path: /etc/apache2/ssl/nexus.vm.key
    mode: 0600

- name: Change permissions on a copied cert
  when: generate_http_cert !=  true
  copy:
    src: "{{ httpd_ssl_certificate_file }}"
    dest: "/etc/pki/tls/certs"
    mode: 0600

- name: Copy SSL certificate key file that was specified
  when: generate_http_cert != true
  copy:
    src: "{{ httpd_ssl_certificate_key_file }}"
    dest: /etc/pki/tls/private
    mode: 0600

#- name: Setsebool httpd_can_network_connect
#  shell: 'setsebool -P httpd_can_network_connect on'
- name: Enable the new https reverse proxy
  shell: sudo a2ensite nexus-vhost.conf

- name: Restart httpd
  service: 
    name: apache2
    state: restarted

- name: Waiting for httpd to be restarted
  wait_for: port=443 delay=5
