---

- name: "Fail if not using Apt or Yum.  Do a manual install for now"
  fail: msg='This role only supports Yum or Apt package managers at the moment.  Please do a manual install instead.'
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'apt'

- name: "yum install Java {{ GOCD_JAVA_PACKAGE_VERSION_YUM }} and some basic dependencies"
  become: yes
  yum: name={{ item }} state=present
  with_items:
   - unzip
   - which
   - "{{ GOCD_JAVA_PACKAGE_YUM }}"
  when: ansible_pkg_mgr == 'yum'

- name: "apt install Java {{ GOCD_JAVA_PACKAGE_VERSION_DEB }} and some basic dependencies. Must be installed before repo."
  become: yes
  apt: name={{ item }} state=present update_cache=true
  with_items:
   - python-pycurl
   - unzip
   - "{{ GOCD_JAVA_PACKAGE_DEB }}"
  when: ansible_pkg_mgr == 'apt'

- name: determine JAVA_HOME
  shell: readlink -f /usr/bin/java | sed "s:bin/java::"
  register: system_java_home
  changed_when: false

- name: set GOCD_JAVA_HOME
  set_fact:
     GOCD_JAVA_HOME: "{{ system_java_home.stdout }}"

- debug:
    msg: "What is the java home? {{ system_java_home.stdout }}"

- name: Ensure that java in /usr/bin/java is actually runnable
  shell: java -version

